# Site settings
title: DGMD S-15
email: dgmds15@gmail.com
description: "Digital Media — Creative Explorations in Screen-Based and Physical Computing at Harvard"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dgmd.github.io" # the base hostname & protocol for your site

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown

collections:
  - sessions
  - nextweeks
  - snippets